/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminHelpRouteImport } from './routes/admin.help'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminSatelliteRouteImport } from './routes/admin.satellite'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CitizenReportRouteImport } from './routes/citizen.report'
import { Route as AdminAssetsIndexRouteImport } from './routes/admin.assets.index'
import { Route as AdminAssetsAssetIdRouteImport } from './routes/admin.assets.$assetId'
import { Route as AdminComplaintsIndexRouteImport } from './routes/admin.complaints.index'
import { Route as AdminComplaintsComplaintIdRouteImport } from './routes/admin.complaints.$complaintId'
import { Route as AdminContractorsIndexRouteImport } from './routes/admin.contractors.index'
import { Route as AdminContractorsContractorIdRouteImport } from './routes/admin.contractors.$contractorId'
import { Route as AdminWorkOrdersIndexRouteImport } from './routes/admin.work-orders.index'
import { Route as AdminWorkOrdersWorkOrderIdRouteImport } from './routes/admin.work-orders.$workOrderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSatelliteRoute = AdminSatelliteRouteImport.update({
  id: '/satellite',
  path: '/satellite',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenReportRoute = CitizenReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => CitizenRoute,
} as any)
const AdminAssetsIndexRoute = AdminAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsAssetIdRoute = AdminAssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsIndexRoute = AdminComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsComplaintIdRoute =
  AdminComplaintsComplaintIdRouteImport.update({
    id: '/complaints/$complaintId',
    path: '/complaints/$complaintId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContractorsIndexRoute = AdminContractorsIndexRouteImport.update({
  id: '/contractors/',
  path: '/contractors/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractorsContractorIdRoute =
  AdminContractorsContractorIdRouteImport.update({
    id: '/contractors/$contractorId',
    path: '/contractors/$contractorId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminWorkOrdersIndexRoute = AdminWorkOrdersIndexRouteImport.update({
  id: '/work-orders/',
  path: '/work-orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkOrdersWorkOrderIdRoute =
  AdminWorkOrdersWorkOrderIdRouteImport.update({
    id: '/work-orders/$workOrderId',
    path: '/work-orders/$workOrderId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/citizen': typeof CitizenRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/satellite': typeof AdminSatelliteRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/citizen/report': typeof CitizenReportRoute
  '/admin/': typeof AdminIndexRoute
  '/citizen/': typeof CitizenIndexRoute
  '/admin/assets/$assetId': typeof AdminAssetsAssetIdRoute
  '/admin/complaints/$complaintId': typeof AdminComplaintsComplaintIdRoute
  '/admin/contractors/$contractorId': typeof AdminContractorsContractorIdRoute
  '/admin/work-orders/$workOrderId': typeof AdminWorkOrdersWorkOrderIdRoute
  '/admin/assets/': typeof AdminAssetsIndexRoute
  '/admin/complaints/': typeof AdminComplaintsIndexRoute
  '/admin/contractors/': typeof AdminContractorsIndexRoute
  '/admin/work-orders/': typeof AdminWorkOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/satellite': typeof AdminSatelliteRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/citizen/report': typeof CitizenReportRoute
  '/admin': typeof AdminIndexRoute
  '/citizen': typeof CitizenIndexRoute
  '/admin/assets/$assetId': typeof AdminAssetsAssetIdRoute
  '/admin/complaints/$complaintId': typeof AdminComplaintsComplaintIdRoute
  '/admin/contractors/$contractorId': typeof AdminContractorsContractorIdRoute
  '/admin/work-orders/$workOrderId': typeof AdminWorkOrdersWorkOrderIdRoute
  '/admin/assets': typeof AdminAssetsIndexRoute
  '/admin/complaints': typeof AdminComplaintsIndexRoute
  '/admin/contractors': typeof AdminContractorsIndexRoute
  '/admin/work-orders': typeof AdminWorkOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/citizen': typeof CitizenRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/satellite': typeof AdminSatelliteRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/citizen/report': typeof CitizenReportRoute
  '/admin/': typeof AdminIndexRoute
  '/citizen/': typeof CitizenIndexRoute
  '/admin/assets/$assetId': typeof AdminAssetsAssetIdRoute
  '/admin/complaints/$complaintId': typeof AdminComplaintsComplaintIdRoute
  '/admin/contractors/$contractorId': typeof AdminContractorsContractorIdRoute
  '/admin/work-orders/$workOrderId': typeof AdminWorkOrdersWorkOrderIdRoute
  '/admin/assets/': typeof AdminAssetsIndexRoute
  '/admin/complaints/': typeof AdminComplaintsIndexRoute
  '/admin/contractors/': typeof AdminContractorsIndexRoute
  '/admin/work-orders/': typeof AdminWorkOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/citizen'
    | '/landing'
    | '/login'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/help'
    | '/admin/map'
    | '/admin/satellite'
    | '/admin/settings'
    | '/citizen/report'
    | '/admin/'
    | '/citizen/'
    | '/admin/assets/$assetId'
    | '/admin/complaints/$complaintId'
    | '/admin/contractors/$contractorId'
    | '/admin/work-orders/$workOrderId'
    | '/admin/assets/'
    | '/admin/complaints/'
    | '/admin/contractors/'
    | '/admin/work-orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/help'
    | '/admin/map'
    | '/admin/satellite'
    | '/admin/settings'
    | '/citizen/report'
    | '/admin'
    | '/citizen'
    | '/admin/assets/$assetId'
    | '/admin/complaints/$complaintId'
    | '/admin/contractors/$contractorId'
    | '/admin/work-orders/$workOrderId'
    | '/admin/assets'
    | '/admin/complaints'
    | '/admin/contractors'
    | '/admin/work-orders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/citizen'
    | '/landing'
    | '/login'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/help'
    | '/admin/map'
    | '/admin/satellite'
    | '/admin/settings'
    | '/citizen/report'
    | '/admin/'
    | '/citizen/'
    | '/admin/assets/$assetId'
    | '/admin/complaints/$complaintId'
    | '/admin/contractors/$contractorId'
    | '/admin/work-orders/$workOrderId'
    | '/admin/assets/'
    | '/admin/complaints/'
    | '/admin/contractors/'
    | '/admin/work-orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CitizenRoute: typeof CitizenRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/satellite': {
      id: '/admin/satellite'
      path: '/satellite'
      fullPath: '/admin/satellite'
      preLoaderRoute: typeof AdminSatelliteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/report': {
      id: '/citizen/report'
      path: '/report'
      fullPath: '/citizen/report'
      preLoaderRoute: typeof CitizenReportRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/admin/assets/': {
      id: '/admin/assets/'
      path: '/assets'
      fullPath: '/admin/assets/'
      preLoaderRoute: typeof AdminAssetsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/$assetId': {
      id: '/admin/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/admin/assets/$assetId'
      preLoaderRoute: typeof AdminAssetsAssetIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints/': {
      id: '/admin/complaints/'
      path: '/complaints'
      fullPath: '/admin/complaints/'
      preLoaderRoute: typeof AdminComplaintsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints/$complaintId': {
      id: '/admin/complaints/$complaintId'
      path: '/complaints/$complaintId'
      fullPath: '/admin/complaints/$complaintId'
      preLoaderRoute: typeof AdminComplaintsComplaintIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contractors/': {
      id: '/admin/contractors/'
      path: '/contractors'
      fullPath: '/admin/contractors/'
      preLoaderRoute: typeof AdminContractorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contractors/$contractorId': {
      id: '/admin/contractors/$contractorId'
      path: '/contractors/$contractorId'
      fullPath: '/admin/contractors/$contractorId'
      preLoaderRoute: typeof AdminContractorsContractorIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/work-orders/': {
      id: '/admin/work-orders/'
      path: '/work-orders'
      fullPath: '/admin/work-orders/'
      preLoaderRoute: typeof AdminWorkOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/work-orders/$workOrderId': {
      id: '/admin/work-orders/$workOrderId'
      path: '/work-orders/$workOrderId'
      fullPath: '/admin/work-orders/$workOrderId'
      preLoaderRoute: typeof AdminWorkOrdersWorkOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminSatelliteRoute: typeof AdminSatelliteRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAssetsAssetIdRoute: typeof AdminAssetsAssetIdRoute
  AdminComplaintsComplaintIdRoute: typeof AdminComplaintsComplaintIdRoute
  AdminContractorsContractorIdRoute: typeof AdminContractorsContractorIdRoute
  AdminWorkOrdersWorkOrderIdRoute: typeof AdminWorkOrdersWorkOrderIdRoute
  AdminAssetsIndexRoute: typeof AdminAssetsIndexRoute
  AdminComplaintsIndexRoute: typeof AdminComplaintsIndexRoute
  AdminContractorsIndexRoute: typeof AdminContractorsIndexRoute
  AdminWorkOrdersIndexRoute: typeof AdminWorkOrdersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminMapRoute: AdminMapRoute,
  AdminSatelliteRoute: AdminSatelliteRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAssetsAssetIdRoute: AdminAssetsAssetIdRoute,
  AdminComplaintsComplaintIdRoute: AdminComplaintsComplaintIdRoute,
  AdminContractorsContractorIdRoute: AdminContractorsContractorIdRoute,
  AdminWorkOrdersWorkOrderIdRoute: AdminWorkOrdersWorkOrderIdRoute,
  AdminAssetsIndexRoute: AdminAssetsIndexRoute,
  AdminComplaintsIndexRoute: AdminComplaintsIndexRoute,
  AdminContractorsIndexRoute: AdminContractorsIndexRoute,
  AdminWorkOrdersIndexRoute: AdminWorkOrdersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CitizenRouteChildren {
  CitizenReportRoute: typeof CitizenReportRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
}

const CitizenRouteChildren: CitizenRouteChildren = {
  CitizenReportRoute: CitizenReportRoute,
  CitizenIndexRoute: CitizenIndexRoute,
}

const CitizenRouteWithChildren =
  CitizenRoute._addFileChildren(CitizenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CitizenRoute: CitizenRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
